__all__ = ["TAGS", "GUI_HEADERS", "EXTENDED_TAGS", "STR_TAGS"]

TAGS = ("ALBUM", "ALBUMARTIST", "ARTIST", "COMPOSER", "COVERART", "DATE",
        "DISCNUMBER", "GENRE", "LYRICS", "TITLE", "TRACKNUMBER")
GUI_HEADERS = ("TRACKNUMBER", "TITLE", "TYPE", "ARTIST", "COMPOSER",
               "DISCNUMBER", "LYRICS", "FILE")
EXTENDED_TAGS = TAGS + ("FILE", "TYPE")
STR_TAGS = ("GENRE", "ALBUM", "ALBUMARTIST", "DATE")
