language: python
jobs:
  include:
    # ===== Linux ======
    - name: "Python 3.6 on Ubuntu 18.04 (Bionic Beaver)"
      dist: bionic
      python: 3.6
      before_install:
      - python --version
      - pip install -U pip
      - pip install coverage
      - pip install -r docs/requirements.txt
    - name: "Python 3.7 on Ubuntu 18.04 (Bionic Beaver)"
      dist: bionic
      python: 3.7
      before_install:
      - python --version
      - pip install -U pip
      - pip install coverage
      - pip install -r docs/requirements.txt
    - name: "Python 3.8 on Ubuntu 18.04 (Bionic Beaver)"
      dist: bionic
      python: 3.8
      before_install:
      - python --version
      - pip install -U pip
      - pip install coverage
      - pip install -r docs/requirements.txt
    # ======= OSX ========
    - name: "Python 3.6.5 on macOS 10.13"
      os: osx
      osx_image: xcode9.4  # Python 3.6.5 running on macOS 10.13
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
        - pip3 install -U pip
        - pip3 install coverage
        - pip3 install -r docs/requirements.txt
      script: python3 -m unittest discover
      after_success: python 3 -m coverage
    - name: "Python 3.7.3 on macOS 10.14"
      os: osx
      osx_image: xcode10.2  # Python 3.7.3 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
        - pip3 install -U pip
        - pip3 install coverage
        - pip3 install -r docs/requirements.txt
      script: python3 -m unittest discover
      after_success: python 3 -m coverage
    #  ====== WINDOWS =========
    - name: "Python 3.6.8 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.6.8
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install coverage
        - pip3 install -r docs/requirements.txt
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    - name: "Python 3.7.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.4
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install coverage
        - pip3 install -r docs/requirements.txt
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
    - name: "Python 3.8.1 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.1
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install coverage
        - pip3 install -r docs/requirements.txt
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install:
  - pip3 install .
script: coverage run -m unittest discover
after_success:
  - coveralls # submit coverage