# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1621, 847)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 220, 1021, 461))
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setRowCount(2)
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setVisible(True)
        self.Input = QtWidgets.QGroupBox(self.centralwidget)
        self.Input.setGeometry(QtCore.QRect(20, 10, 591, 91))
        self.Input.setObjectName("Input")
        self.gridLayout = QtWidgets.QGridLayout(self.Input)
        self.gridLayout.setObjectName("gridLayout")
        self.display_dir = QtWidgets.QLineEdit(self.Input)
        self.display_dir.setToolTip("")
        self.display_dir.setStatusTip("")
        self.display_dir.setWhatsThis("")
        self.display_dir.setAccessibleDescription("")
        self.display_dir.setObjectName("display_dir")
        self.gridLayout.addWidget(self.display_dir, 0, 0, 1, 4)
        self.label = QtWidgets.QLabel(self.Input)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.band_entry = QtWidgets.QLineEdit(self.Input)
        self.band_entry.setObjectName("band_entry")
        self.gridLayout.addWidget(self.band_entry, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.Input)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        self.album_entry = QtWidgets.QLineEdit(self.Input)
        self.album_entry.setObjectName("album_entry")
        self.gridLayout.addWidget(self.album_entry, 1, 3, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 120, 593, 85))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 3, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 1, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_2.addWidget(self.lineEdit_5, 1, 1, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_2.addWidget(self.lineEdit_6, 1, 2, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_2.addWidget(self.lineEdit_7, 1, 3, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(1050, 10, 291, 671))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 2, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_4.addWidget(self.textEdit, 11, 0, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_4.addWidget(self.lineEdit_10, 7, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 4, 0, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_4.addWidget(self.lineEdit_9, 5, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 6, 0, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_4.addWidget(self.lineEdit_11, 9, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 8, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 10, 0, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_4.addWidget(self.lineEdit_8, 3, 0, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_4.addWidget(self.lineEdit_12, 1, 0, 1, 1)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(640, 30, 95, 100))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.browse_button = QtWidgets.QPushButton(self.layoutWidget)
        self.browse_button.setObjectName("browse_button")
        self.gridLayout_3.addWidget(self.browse_button, 0, 0, 1, 1)
        self.run_button = QtWidgets.QPushButton(self.layoutWidget)
        self.run_button.setObjectName("run_button")
        self.gridLayout_3.addWidget(self.run_button, 1, 0, 1, 1)
        self.lyrics_button = QtWidgets.QPushButton(self.layoutWidget)
        self.lyrics_button.setObjectName("lyrics_button")
        self.gridLayout_3.addWidget(self.lyrics_button, 2, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(1030, 10, 20, 671))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(770, 30, 112, 49))
        self.widget.setObjectName("widget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.json_write = QtWidgets.QCheckBox(self.widget)
        self.json_write.setObjectName("json_write")
        self.gridLayout_5.addWidget(self.json_write, 0, 0, 1, 1)
        self.offline_debug = QtWidgets.QCheckBox(self.widget)
        self.offline_debug.setObjectName("offline_debug")
        self.gridLayout_5.addWidget(self.offline_debug, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1621, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOpen = QtWidgets.QMenu(self.menubar)
        self.menuOpen.setObjectName("menuOpen")
        self.menuSave = QtWidgets.QMenu(self.menubar)
        self.menuSave.setObjectName("menuSave")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAll_Tags = QtWidgets.QAction(MainWindow)
        self.actionAll_Tags.setObjectName("actionAll_Tags")
        self.actionOnly_Lyrics = QtWidgets.QAction(MainWindow)
        self.actionOnly_Lyrics.setObjectName("actionOnly_Lyrics")
        self.actionDirectory = QtWidgets.QAction(MainWindow)
        self.actionDirectory.setObjectName("actionDirectory")
        self.actionWikipedia = QtWidgets.QAction(MainWindow)
        self.actionWikipedia.setObjectName("actionWikipedia")
        self.actionCover_Art_search = QtWidgets.QAction(MainWindow)
        self.actionCover_Art_search.setObjectName("actionCover_Art_search")
        self.actionMp3_Tag = QtWidgets.QAction(MainWindow)
        self.actionMp3_Tag.setObjectName("actionMp3_Tag")
        self.actionHelp_Index = QtWidgets.QAction(MainWindow)
        self.actionHelp_Index.setObjectName("actionHelp_Index")
        self.actionGit = QtWidgets.QAction(MainWindow)
        self.actionGit.setObjectName("actionGit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuOpen.addAction(self.actionDirectory)
        self.menuOpen.addAction(self.actionWikipedia)
        self.menuOpen.addAction(self.actionCover_Art_search)
        self.menuOpen.addAction(self.actionMp3_Tag)
        self.menuSave.addAction(self.actionAll_Tags)
        self.menuSave.addAction(self.actionOnly_Lyrics)
        self.menuHelp.addAction(self.actionHelp_Index)
        self.menuHelp.addAction(self.actionGit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOpen.menuAction())
        self.menubar.addAction(self.menuSave.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Input.setTitle(_translate("MainWindow", "Input"))
        self.label.setText(_translate("MainWindow", "Input Artist"))
        self.label_2.setText(_translate("MainWindow", "Input Album"))
        self.groupBox.setTitle(_translate("MainWindow", "Common Tags"))
        self.label_3.setText(_translate("MainWindow", "Album Artist"))
        self.label_4.setText(_translate("MainWindow", "Album"))
        self.label_5.setText(_translate("MainWindow", "Year"))
        self.label_6.setText(_translate("MainWindow", "Genre"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Detail"))
        self.label_8.setText(_translate("MainWindow", "Number"))
        self.label_9.setText(_translate("MainWindow", "Artists"))
        self.label_10.setText(_translate("MainWindow", "Composers"))
        self.label_7.setText(_translate("MainWindow", "Song title"))
        self.label_11.setText(_translate("MainWindow", "File"))
        self.label_12.setText(_translate("MainWindow", "Lyrics"))
        self.browse_button.setText(_translate("MainWindow", "browse"))
        self.run_button.setText(_translate("MainWindow", "Wiki Search"))
        self.lyrics_button.setText(_translate("MainWindow", "Lyrics search"))
        self.json_write.setText(_translate("MainWindow", "Write json?"))
        self.offline_debug.setText(_translate("MainWindow", "Offline debug?"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOpen.setTitle(_translate("MainWindow", "Open"))
        self.menuSave.setTitle(_translate("MainWindow", "Save"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAll_Tags.setText(_translate("MainWindow", "All Tags"))
        self.actionOnly_Lyrics.setText(_translate("MainWindow", "Only Lyrics"))
        self.actionDirectory.setText(_translate("MainWindow", "Directory"))
        self.actionWikipedia.setText(_translate("MainWindow", "Wikipedia"))
        self.actionCover_Art_search.setText(_translate("MainWindow", "Cover Art search"))
        self.actionMp3_Tag.setText(_translate("MainWindow", "Mp3Tag"))
        self.actionHelp_Index.setText(_translate("MainWindow", "Help Index"))
        self.actionGit.setText(_translate("MainWindow", "Git"))
        self.actionAbout.setText(_translate("MainWindow", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

