# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'art_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(1021, 856)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dialog.sizePolicy().hasHeightForWidth())
        dialog.setSizePolicy(sizePolicy)
        self.gridLayout_2 = QtWidgets.QGridLayout(dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(dialog)
        self.groupBox.setMaximumSize(QtCore.QSize(250, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 70, 211, 81))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.size_spinbox_Y = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.size_spinbox_Y.setMinimum(10)
        self.size_spinbox_Y.setMaximum(2000)
        self.size_spinbox_Y.setProperty("value", 1400)
        self.size_spinbox_Y.setObjectName("size_spinbox_Y")
        self.gridLayout.addWidget(self.size_spinbox_Y, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.size_spinbox_X = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.size_spinbox_X.setMinimum(10)
        self.size_spinbox_X.setMaximum(2000)
        self.size_spinbox_X.setProperty("value", 1400)
        self.size_spinbox_X.setObjectName("size_spinbox_X")
        self.gridLayout.addWidget(self.size_spinbox_X, 2, 1, 1, 1)
        self.ca_file = QtWidgets.QCheckBox(self.groupBox)
        self.ca_file.setGeometry(QtCore.QRect(10, 710, 241, 20))
        self.ca_file.setObjectName("ca_file")
        self.ca_clipboard = QtWidgets.QCheckBox(self.groupBox)
        self.ca_clipboard.setGeometry(QtCore.QRect(10, 740, 221, 20))
        self.ca_clipboard.setChecked(True)
        self.ca_clipboard.setObjectName("ca_clipboard")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 30, 171, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.ca_ratio = QtWidgets.QCheckBox(self.groupBox)
        self.ca_ratio.setGeometry(QtCore.QRect(20, 170, 121, 20))
        self.ca_ratio.setObjectName("ca_ratio")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 240, 61, 21))
        self.label_4.setObjectName("label_4")
        self.ca_dropdown = QtWidgets.QComboBox(self.groupBox)
        self.ca_dropdown.setGeometry(QtCore.QRect(20, 270, 111, 22))
        self.ca_dropdown.setEditable(True)
        self.ca_dropdown.setObjectName("ca_dropdown")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 360, 61, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(150, 270, 81, 16))
        self.label_6.setObjectName("label_6")
        self.compresion_slider = QtWidgets.QSlider(self.groupBox)
        self.compresion_slider.setGeometry(QtCore.QRect(20, 420, 160, 22))
        self.compresion_slider.setMinimum(1)
        self.compresion_slider.setMaximum(100)
        self.compresion_slider.setOrientation(QtCore.Qt.Horizontal)
        self.compresion_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.compresion_slider.setTickInterval(10)
        self.compresion_slider.setObjectName("compresion_slider")
        self.compresion_spinbox = QtWidgets.QSpinBox(self.groupBox)
        self.compresion_spinbox.setGeometry(QtCore.QRect(190, 420, 42, 22))
        self.compresion_spinbox.setMinimum(1)
        self.compresion_spinbox.setMaximum(100)
        self.compresion_spinbox.setObjectName("compresion_spinbox")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(20, 400, 91, 16))
        self.label_7.setObjectName("label_7")
        self.size_label = QtWidgets.QLabel(self.groupBox)
        self.size_label.setGeometry(QtCore.QRect(20, 460, 55, 16))
        self.size_label.setObjectName("size_label")
        self.size_box = QtWidgets.QLineEdit(self.groupBox)
        self.size_box.setGeometry(QtCore.QRect(80, 460, 113, 22))
        self.size_box.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.size_box.setObjectName("size_box")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(200, 460, 31, 16))
        self.label_8.setObjectName("label_8")
        self.apply_ratio = QtWidgets.QPushButton(self.groupBox)
        self.apply_ratio.setGeometry(QtCore.QRect(20, 200, 93, 28))
        self.apply_ratio.setObjectName("apply_ratio")
        self.apply_crop = QtWidgets.QPushButton(self.groupBox)
        self.apply_crop.setGeometry(QtCore.QRect(20, 310, 93, 28))
        self.apply_crop.setObjectName("apply_crop")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.groupBox)
        self.buttonBox.setGeometry(QtCore.QRect(20, 790, 201, 28))
        self.buttonBox.setMaximumSize(QtCore.QSize(250, 16777215))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.cancel_crop = QtWidgets.QPushButton(self.groupBox)
        self.cancel_crop.setGeometry(QtCore.QRect(130, 310, 93, 28))
        self.cancel_crop.setObjectName("cancel_crop")
        self.gridLayout_2.addWidget(self.groupBox, 0, 1, 1, 1)
        self.picture_frame = QtWidgets.QGridLayout()
        self.picture_frame.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.picture_frame.setObjectName("picture_frame")
        self.gridLayout_2.addLayout(self.picture_frame, 0, 0, 1, 1)

        self.retranslateUi(dialog)
        self.buttonBox.accepted.connect(dialog.accept)
        self.buttonBox.rejected.connect(dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Dialog"))
        self.groupBox.setTitle(_translate("dialog", "Control"))
        self.label_2.setText(_translate("dialog", "X:"))
        self.label_3.setText(_translate("dialog", "Y:"))
        self.ca_file.setText(_translate("dialog", "Export Cover Art to file (Folder.jpg)"))
        self.ca_clipboard.setText(_translate("dialog", "Copy Cover Art to clipboard"))
        self.label.setText(_translate("dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Resize</span></p></body></html>"))
        self.ca_ratio.setText(_translate("dialog", "Fix aspect ratio"))
        self.label_4.setText(_translate("dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Crop</span></p></body></html>"))
        self.ca_dropdown.setCurrentText(_translate("dialog", "preserve"))
        self.label_5.setText(_translate("dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Save</span></p></body></html>"))
        self.label_6.setText(_translate("dialog", "aspect ratio"))
        self.label_7.setText(_translate("dialog", "Compresion"))
        self.size_label.setText(_translate("dialog", "Final size: "))
        self.label_8.setText(_translate("dialog", "Kb"))
        self.apply_ratio.setText(_translate("dialog", "Apply"))
        self.apply_crop.setText(_translate("dialog", "Apply"))
        self.cancel_crop.setText(_translate("dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog = QtWidgets.QDialog()
    ui = Ui_dialog()
    ui.setupUi(dialog)
    dialog.show()
    sys.exit(app.exec_())

