# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'art_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1021, 856)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setMaximumSize(QtCore.QSize(250, 16777215))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 4, 1, 1, 1)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 4, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setMaximumSize(QtCore.QSize(250, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 70, 211, 81))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.size_spinbox_Y = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.size_spinbox_Y.setMinimum(10)
        self.size_spinbox_Y.setMaximum(2000)
        self.size_spinbox_Y.setProperty("value", 1400)
        self.size_spinbox_Y.setObjectName("size_spinbox_Y")
        self.gridLayout.addWidget(self.size_spinbox_Y, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.size_spinbox_X = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.size_spinbox_X.setMinimum(10)
        self.size_spinbox_X.setMaximum(2000)
        self.size_spinbox_X.setProperty("value", 1400)
        self.size_spinbox_X.setObjectName("size_spinbox_X")
        self.gridLayout.addWidget(self.size_spinbox_X, 2, 1, 1, 1)
        self.ca_file = QtWidgets.QCheckBox(self.groupBox)
        self.ca_file.setGeometry(QtCore.QRect(10, 440, 241, 20))
        self.ca_file.setObjectName("ca_file")
        self.ca_clipboard = QtWidgets.QCheckBox(self.groupBox)
        self.ca_clipboard.setGeometry(QtCore.QRect(10, 410, 221, 20))
        self.ca_clipboard.setChecked(True)
        self.ca_clipboard.setObjectName("ca_clipboard")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 30, 171, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.ca_ratio = QtWidgets.QCheckBox(self.groupBox)
        self.ca_ratio.setGeometry(QtCore.QRect(20, 170, 121, 20))
        self.ca_ratio.setObjectName("ca_ratio")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 210, 61, 21))
        self.label_4.setObjectName("label_4")
        self.ca_dropdown = QtWidgets.QComboBox(self.groupBox)
        self.ca_dropdown.setGeometry(QtCore.QRect(20, 250, 111, 22))
        self.ca_dropdown.setEditable(True)
        self.ca_dropdown.setObjectName("ca_dropdown")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 300, 61, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(150, 250, 81, 16))
        self.label_6.setObjectName("label_6")
        self.compresion_slider = QtWidgets.QSlider(self.groupBox)
        self.compresion_slider.setGeometry(QtCore.QRect(20, 370, 160, 22))
        self.compresion_slider.setOrientation(QtCore.Qt.Horizontal)
        self.compresion_slider.setObjectName("compresion_slider")
        self.compresion_spinbox = QtWidgets.QSpinBox(self.groupBox)
        self.compresion_spinbox.setGeometry(QtCore.QRect(190, 370, 42, 22))
        self.compresion_spinbox.setObjectName("compresion_spinbox")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(20, 330, 91, 16))
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.groupBox, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Control"))
        self.label_2.setText(_translate("Dialog", "X:"))
        self.label_3.setText(_translate("Dialog", "Y:"))
        self.ca_file.setText(_translate("Dialog", "Export Cover Art to file (Folder.jpg)"))
        self.ca_clipboard.setText(_translate("Dialog", "Copy Cover Art to clipboard"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Resize</span></p></body></html>"))
        self.ca_ratio.setText(_translate("Dialog", "Fix aspect ratio"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Crop</span></p></body></html>"))
        self.ca_dropdown.setCurrentText(_translate("Dialog", "preserve"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Save</span></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "aspect ratio"))
        self.label_7.setText(_translate("Dialog", "Compresion"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

