# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qt_layout.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1401, 742)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.picture_layout = QtWidgets.QHBoxLayout()
        self.picture_layout.setObjectName("picture_layout")
        self.gridLayout.addLayout(self.picture_layout, 0, 3, 2, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 4, 3, 1)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setSortingEnabled(False)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setSortIndicatorShown(True)
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.verticalHeader().setVisible(False)
        self.tableView.verticalHeader().setDefaultSectionSize(25)
        self.tableView.verticalHeader().setMinimumSectionSize(20)
        self.tableView.verticalHeader().setSortIndicatorShown(True)
        self.tableView.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tableView, 2, 0, 1, 4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.json_write_sw = QtWidgets.QCheckBox(self.centralwidget)
        self.json_write_sw.setMaximumSize(QtCore.QSize(109, 16777215))
        self.json_write_sw.setObjectName("json_write_sw")
        self.verticalLayout_3.addWidget(self.json_write_sw)
        self.offline_debbug_sw = QtWidgets.QCheckBox(self.centralwidget)
        self.offline_debbug_sw.setMaximumSize(QtCore.QSize(109, 16777215))
        self.offline_debbug_sw.setObjectName("offline_debbug_sw")
        self.verticalLayout_3.addWidget(self.offline_debbug_sw)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 2, 1, 1)
        self.input_frame = QtWidgets.QGroupBox(self.centralwidget)
        self.input_frame.setMaximumSize(QtCore.QSize(600, 16777215))
        self.input_frame.setObjectName("input_frame")
        self.input_grid = QtWidgets.QGridLayout(self.input_frame)
        self.input_grid.setObjectName("input_grid")
        self.display_dir = QtWidgets.QLineEdit(self.input_frame)
        self.display_dir.setToolTip("")
        self.display_dir.setStatusTip("")
        self.display_dir.setWhatsThis("")
        self.display_dir.setAccessibleDescription("")
        self.display_dir.setObjectName("display_dir")
        self.input_grid.addWidget(self.display_dir, 0, 0, 1, 4)
        self.label = QtWidgets.QLabel(self.input_frame)
        self.label.setObjectName("label")
        self.input_grid.addWidget(self.label, 1, 0, 1, 1)
        self.band_entry_input = QtWidgets.QLineEdit(self.input_frame)
        self.band_entry_input.setObjectName("band_entry_input")
        self.input_grid.addWidget(self.band_entry_input, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.input_frame)
        self.label_2.setObjectName("label_2")
        self.input_grid.addWidget(self.label_2, 1, 2, 1, 1)
        self.album_entry_input = QtWidgets.QLineEdit(self.input_frame)
        self.album_entry_input.setObjectName("album_entry_input")
        self.input_grid.addWidget(self.album_entry_input, 1, 3, 1, 1)
        self.gridLayout.addWidget(self.input_frame, 0, 0, 1, 1)
        self.common_tags_frame = QtWidgets.QGroupBox(self.centralwidget)
        self.common_tags_frame.setMaximumSize(QtCore.QSize(600, 16777215))
        self.common_tags_frame.setObjectName("common_tags_frame")
        self.common_tags_grid = QtWidgets.QGridLayout(self.common_tags_frame)
        self.common_tags_grid.setObjectName("common_tags_grid")
        self.label_3 = QtWidgets.QLabel(self.common_tags_frame)
        self.label_3.setObjectName("label_3")
        self.common_tags_grid.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.common_tags_frame)
        self.label_4.setObjectName("label_4")
        self.common_tags_grid.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.common_tags_frame)
        self.label_5.setObjectName("label_5")
        self.common_tags_grid.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.common_tags_frame)
        self.label_6.setObjectName("label_6")
        self.common_tags_grid.addWidget(self.label_6, 0, 3, 1, 1)
        self.band_entry = QtWidgets.QLineEdit(self.common_tags_frame)
        self.band_entry.setObjectName("band_entry")
        self.common_tags_grid.addWidget(self.band_entry, 1, 0, 1, 1)
        self.album_entry = QtWidgets.QLineEdit(self.common_tags_frame)
        self.album_entry.setObjectName("album_entry")
        self.common_tags_grid.addWidget(self.album_entry, 1, 1, 1, 1)
        self.year_entry = QtWidgets.QLineEdit(self.common_tags_frame)
        self.year_entry.setObjectName("year_entry")
        self.common_tags_grid.addWidget(self.year_entry, 1, 2, 1, 1)
        self.genre_entry = QtWidgets.QLineEdit(self.common_tags_frame)
        self.genre_entry.setObjectName("genre_entry")
        self.common_tags_grid.addWidget(self.genre_entry, 1, 3, 1, 1)
        self.gridLayout.addWidget(self.common_tags_frame, 1, 0, 1, 1)
        self.detail_frame = QtWidgets.QGroupBox(self.centralwidget)
        self.detail_frame.setMinimumSize(QtCore.QSize(321, 0))
        self.detail_frame.setMaximumSize(QtCore.QSize(321, 16777215))
        self.detail_frame.setObjectName("detail_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.detail_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(self.detail_frame)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.title_detail = QtWidgets.QLineEdit(self.detail_frame)
        self.title_detail.setObjectName("title_detail")
        self.verticalLayout.addWidget(self.title_detail)
        self.label_8 = QtWidgets.QLabel(self.detail_frame)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.number_detail = QtWidgets.QLineEdit(self.detail_frame)
        self.number_detail.setObjectName("number_detail")
        self.verticalLayout.addWidget(self.number_detail)
        self.label_9 = QtWidgets.QLabel(self.detail_frame)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.artist_detail = QtWidgets.QLineEdit(self.detail_frame)
        self.artist_detail.setObjectName("artist_detail")
        self.verticalLayout.addWidget(self.artist_detail)
        self.label_10 = QtWidgets.QLabel(self.detail_frame)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.composer_detail = QtWidgets.QLineEdit(self.detail_frame)
        self.composer_detail.setObjectName("composer_detail")
        self.verticalLayout.addWidget(self.composer_detail)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_11 = QtWidgets.QLabel(self.detail_frame)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.toolButton = QtWidgets.QToolButton(self.detail_frame)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.file_detail = QtWidgets.QLineEdit(self.detail_frame)
        self.file_detail.setObjectName("file_detail")
        self.verticalLayout.addWidget(self.file_detail)
        self.label_12 = QtWidgets.QLabel(self.detail_frame)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.lyrics_detail = QtWidgets.QTextEdit(self.detail_frame)
        self.lyrics_detail.setObjectName("lyrics_detail")
        self.verticalLayout.addWidget(self.lyrics_detail)
        self.gridLayout.addWidget(self.detail_frame, 0, 5, 3, 1)
        self.buttons_grid = QtWidgets.QGridLayout()
        self.buttons_grid.setObjectName("buttons_grid")
        self.browse_button = QtWidgets.QPushButton(self.centralwidget)
        self.browse_button.setMaximumSize(QtCore.QSize(93, 16777215))
        self.browse_button.setObjectName("browse_button")
        self.buttons_grid.addWidget(self.browse_button, 0, 0, 1, 1)
        self.lyrics_button = QtWidgets.QPushButton(self.centralwidget)
        self.lyrics_button.setMaximumSize(QtCore.QSize(93, 16777215))
        self.lyrics_button.setObjectName("lyrics_button")
        self.buttons_grid.addWidget(self.lyrics_button, 2, 0, 1, 1)
        self.wiki_search_button = QtWidgets.QPushButton(self.centralwidget)
        self.wiki_search_button.setMaximumSize(QtCore.QSize(93, 16777215))
        self.wiki_search_button.setObjectName("wiki_search_button")
        self.buttons_grid.addWidget(self.wiki_search_button, 1, 0, 1, 1)
        self.coverArt = QtWidgets.QPushButton(self.centralwidget)
        self.coverArt.setObjectName("coverArt")
        self.buttons_grid.addWidget(self.coverArt, 3, 0, 1, 1)
        self.gridLayout.addLayout(self.buttons_grid, 0, 1, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1401, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOpen = QtWidgets.QMenu(self.menubar)
        self.menuOpen.setObjectName("menuOpen")
        self.menuSave = QtWidgets.QMenu(self.menubar)
        self.menuSave.setObjectName("menuSave")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAll_Tags = QtWidgets.QAction(MainWindow)
        self.actionAll_Tags.setObjectName("actionAll_Tags")
        self.actionOnly_Lyrics = QtWidgets.QAction(MainWindow)
        self.actionOnly_Lyrics.setObjectName("actionOnly_Lyrics")
        self.actionDirectory = QtWidgets.QAction(MainWindow)
        self.actionDirectory.setObjectName("actionDirectory")
        self.actionWikipedia = QtWidgets.QAction(MainWindow)
        self.actionWikipedia.setObjectName("actionWikipedia")
        self.actionCover_Art_search = QtWidgets.QAction(MainWindow)
        self.actionCover_Art_search.setObjectName("actionCover_Art_search")
        self.actionMp3_Tag = QtWidgets.QAction(MainWindow)
        self.actionMp3_Tag.setObjectName("actionMp3_Tag")
        self.actionHelp_Index = QtWidgets.QAction(MainWindow)
        self.actionHelp_Index.setObjectName("actionHelp_Index")
        self.actionGit = QtWidgets.QAction(MainWindow)
        self.actionGit.setObjectName("actionGit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuOpen.addAction(self.actionDirectory)
        self.menuOpen.addAction(self.actionWikipedia)
        self.menuOpen.addAction(self.actionCover_Art_search)
        self.menuOpen.addAction(self.actionMp3_Tag)
        self.menuSave.addAction(self.actionAll_Tags)
        self.menuSave.addAction(self.actionOnly_Lyrics)
        self.menuHelp.addAction(self.actionHelp_Index)
        self.menuHelp.addAction(self.actionGit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOpen.menuAction())
        self.menubar.addAction(self.menuSave.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.json_write_sw.setText(_translate("MainWindow", "Write json?"))
        self.offline_debbug_sw.setText(_translate("MainWindow", "Offline debug?"))
        self.input_frame.setTitle(_translate("MainWindow", "Input"))
        self.label.setText(_translate("MainWindow", "Input Artist"))
        self.label_2.setText(_translate("MainWindow", "Input Album"))
        self.common_tags_frame.setTitle(_translate("MainWindow", "Common Tags"))
        self.label_3.setText(_translate("MainWindow", "Album Artist"))
        self.label_4.setText(_translate("MainWindow", "Album"))
        self.label_5.setText(_translate("MainWindow", "Year"))
        self.label_6.setText(_translate("MainWindow", "Genre"))
        self.detail_frame.setTitle(_translate("MainWindow", "Detail"))
        self.label_7.setText(_translate("MainWindow", "Song title"))
        self.label_8.setText(_translate("MainWindow", "Number"))
        self.label_9.setText(_translate("MainWindow", "Artists"))
        self.label_10.setText(_translate("MainWindow", "Composers"))
        self.label_11.setText(_translate("MainWindow", "File"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.label_12.setText(_translate("MainWindow", "Lyrics"))
        self.browse_button.setText(_translate("MainWindow", "browse"))
        self.lyrics_button.setText(_translate("MainWindow", "Lyrics search"))
        self.wiki_search_button.setText(_translate("MainWindow", "Wiki Search"))
        self.coverArt.setText(_translate("MainWindow", "Cover Art"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOpen.setTitle(_translate("MainWindow", "Open"))
        self.menuSave.setTitle(_translate("MainWindow", "Save"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAll_Tags.setText(_translate("MainWindow", "All Tags"))
        self.actionOnly_Lyrics.setText(_translate("MainWindow", "Only Lyrics"))
        self.actionDirectory.setText(_translate("MainWindow", "Directory"))
        self.actionWikipedia.setText(_translate("MainWindow", "Wikipedia"))
        self.actionCover_Art_search.setText(_translate("MainWindow", "Cover Art search"))
        self.actionMp3_Tag.setText(_translate("MainWindow", "Mp3Tag"))
        self.actionHelp_Index.setText(_translate("MainWindow", "Help Index"))
        self.actionGit.setText(_translate("MainWindow", "Git"))
        self.actionAbout.setText(_translate("MainWindow", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

